export ANSIBLE_PATH=/opt/ansible

export ANSIBLE_CALLBACK_PLUGINS=$ANSIBLE_PATH/callback_plugins
export ANSIBLE_LIBRARY=$ANSIBLE_PATH/library
export ANSIBLE_LOG_PATH=$ANSIBLE_PATH/log/ansible.log
export ANSIBLE_ROLES=$ANSIBLE_PATH/roles
export ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES
export ANSIBLE_PLAYS_PATH=$ANSIBLE_PATH/plays
export ANSIBLE_CONFIG=$ANSIBLE_PLAYS_PATH/ansible.cfg

export ANSIBLE_FORCE_COLOR=true
export ANSIBLE_HOST_KEY_CHECKING=False
export PROFILE_TASKS_TASK_OUTPUT_LIMIT=all
export PYTHONUNBUFFERED=1
